#!/bin/sh
#
set -x
export SDATE=2022073000
#export MEM=000
WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure
export RUNDIR=${TEMP}/${SDATE}/${MEM}
#rm -rf ${TEMP}/${SDATE} 
echo $RUNDIR
#
#export RUNENV='mpiexec -s all -n '${NPES}
 export RUNENV='/usr/local/mpi/openmpi/bin/mpiexec --oversubscribe -n '${NPES}
$JSHDIR/rsm_fcst.sh  
