#!/bin/sh

#############################
#### set all definitions ####
#############################
export SDATE=2022071200
#export MEM=000
WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure
export RUNDIR=${TEMP}/${SDATE}/${MEM}
echo $RUNDIR
rm -rf ${TEMP}/${SDATE}/${MEM}
###########################
#### download gfs data ####
###########################
if [ $RDA = 'no' ]; then
$USHDIR/download_gefs.sh
else
$USHDIR/download_gfspy.sh
fi
#####################
#### excute fcst ####
#####################
#ulimit -s unlimited
$JSHDIR/rsm_fcst.sh  
