#!/bin/sh

#############################
#### set all definitions ####
#############################
export SDATE=${SDATE:-2022061600}
yyyy=`echo $SDATE | cut -c1-4`
if [ $yyyy -lt 2021 ];then
  export IQVAR=2
fi
WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure
echo $RUNDIR
#rm -rf ${TEMP}/${SDATE}
###########################
#### download gfs data ####
###########################
if [ do$RDA = doyes ]; then
$USHDIR/download_gfspy.sh
else
$USHDIR/download_gfs.sh
fi
#####################
#### excute fcst ####
#####################
#ulimit -s unlimited
$JSHDIR/rsm_fcst.sh  
