#!/bin/sh
#
set -x
export SDATE=${SDATE:-2022061000}
export SAMPLETXT="gfs_sampledate_MJ.txt"

WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure 
echo $ENDHOUR $BASEDIR0 $RUNDIR0
echo $HEAD $HEAD2
#exit
#
#export RUNENV='mpiexec -s all -n '${NPES}
 export RUNENV='/opt/local/bin/mpiexec --oversubscribe -n '${NPES}
 export PYENV='/opt/local/bin/python'
$JSHDIR/rsm_ensda.sh  
