#!/bin/sh
#
set -x
export SDATE=${SDATE:-2022061612}
#export MEM=000
WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure
#rm -rf ${TEMP}/${SDATE} 
echo $RUNDIR
#exit
#
#export RUNENV='mpiexec -s all -n '${NPES}
 export RUNENV='/usr/local/mpi/openmpi/bin/mpiexec --oversubscribe -n '${NPES}
$JSHDIR/rsm_fcst.sh  
