#!/bin/sh
#
set -x
export SDATE=${SDATE:-2022083000}
export MEM=${MEM:-000}
export SIGN=${SIGN}
export BV=${BV:-no}
export BP=${BP}
export CYCLE=${CYCLE:-0}
export BV_H=${BV_H:-6}
export TETYPE=${TETYPE}
export SCL=${SCL}
export QADJ=${QADJ:-no}
if [ $CYCLE -gt 1 ]; then
   PCYCLE=`expr $CYCLE - 1`
   fh=`expr $BV_H \* $PCYCLE`
   SDATE=`date -j -f "%Y%m%d%H" -v+${fh}H +"%Y%m%d%H" "${SDATE}"`
   export SDATE
   EXTEND=`expr $fh % 24`
fi
SPINUP=`expr 24 / $BV_H + 1`

WDIR=${WDIR:-` pwd `}
. ${WDIR}/configure 
if [ $CYCLE -lt $SPINUP ] || [ $EXTEND -ne 0 ];then
export ENDHOUR=${BV_H}
fi
echo $ENDHOUR $BASEDIR $RUNDIR
#exit
#
#export RUNENV='mpiexec -s all -n '${NPES}
 export RUNENV='/usr/local/mpi/openmpi/bin/mpiexec --oversubscribe -n '${NPES}
$JSHDIR/rsm_fcst.sh  
